#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
FROM hyperledger/fabric-ca-tools:latest
RUN /bin/sh -c 'curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && curl -o /etc/apt/sources.list.d/microsoft.list https://packages.microsoft.com/config/ubuntu/16.04/prod.list && apt-get update && apt-get install -y powershell'